### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by fjukstad** [kortschak/arrgh#17]
Hi,

Cool project! I just came across the paper and thought I'd let you know I did some work on an OpenCPU interface from Go a while back. I mainly worked on calling functions in R. You can find the package [here](https://github.com/fjukstad/kvik/tree/master/gopencpu) and here's an example as well:

```
package main

import (
	"fmt"

	"github.com/fjukstad/kvik/gopencpu"
)

func main() {

	g := gopencpu.GoOpenCPU{"http://public.opencpu.org", "", ""}

	a, err := g.Rpc("stats/R/rnorm", `{"n":10, "mean": 10, "sd":10}`, "json")
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println(a)

	b, err := g.Rpc("stats/R/rnorm", `{"n":10, "mean": 10, "sd":10}`, "csv")
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(b)

	err = g.Plot("graphics/R/hist", `{"x": [1,2,5,1,20,12,11,5,4,6,10]}`,
		"png", "histogram.png")

	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("histogram stored in histogram.png")

}
```

Anyways, cool stuff! 

Bjørn

**Comment by kortschak** [comment]
Thanks. Your package does some nice helper work that arrgh lack. It might be worth adding some of those in into a helper package. Do you have any suggestions?

I'll close this as "Comment only", but if you do have suggestions, please open issues for them.
